//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sccsr15forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sccsr15forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cbuffer MatrixBuffer :register(b0)
        ///{
        ///	float4x4 world;
        ///	float4x4 view;
        ///	float4x4 proj;
        ///};
        ///
        ///Texture2D diffuseMap;
        ///SamplerState textureSampler;
        ///
        ///struct VS_INPUT
        ///{
        ///    float4 position : POSITION;
        ///	float4 color : COLOR;
        ///	float3 normal : NORMAL;
        ///    float2 tex : TEXCOORD;
        ///	float3 instancePosition : POSITION1;
        ///};
        ///
        ///struct GS_INPUT
        ///{
        ///	float4 position : SV_POSITION;
        ///	float4 color : COLOR;
        ///	float3 normal : NORMAL;
        ///    float2 tex : TEXCOORD;
        ///};
        ///
        ///struct PS_INPUT
        ///{
        ///    float4 position : SV_PO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string geometryshaderLevel {
            get {
                return ResourceManager.GetString("geometryshaderLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////////////////////////
        ///////   GLOBALS
        /////////////////////////
        ///Texture2D shaderTexture;
        ///SamplerState SampleType;
        ///
        ///SamplerState textureSampler
        ///{
        ///    Filter = MIN_MAG_MIP_LINEAR;
        ///    AddressU = Wrap;
        ///    AddressV = Wrap;
        ///};
        ///
        ///
        ////*cbuffer LightBuffer
        ///{
        ///	float4 ambientColor;
        ///	float4 diffuseColor;
        ///	float3 lightDirection;
        ///	float padding;
        ///};*/
        ///
        ///cbuffer LightBuffer //:register(b1)
        ///{
        ///	float4 ambientColor;
        ///	float4 diffuseColor;
        ///	float4 specularColor;
        ///	float4 lightDirection;
        ///	float4 lightPosit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textureTrigLevelPS {
            get {
                return ResourceManager.GetString("textureTrigLevelPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////////////////
        ///// GLOBALS //
        ////////////////
        ///cbuffer MatrixBuffer :register(b0)
        ///{
        ///	float4x4 world;
        ///	float4x4 view;
        ///	float4x4 proj;
        ///};
        ///
        ///cbuffer LightBuffer :register(b1)
        ///{
        ///	float4 ambientColor;
        ///	float4 diffuseColor;
        ///	float3 lightDirection;
        ///	float padding;
        ///};
        ///
        ///
        ///
        /////////////////
        ///// TYPEDEFS //
        /////////////////
        ///struct VertexInputType
        ///{
        ///	float4 position : POSITION0;
        ///	float4 color : COLOR0; //byte map index xyz and w for typeofface 0 to 5
        ///	float3 normal : NORMAL0;
        ///	float paddingvert0 : PSI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textureTrigLevelVS {
            get {
                return ResourceManager.GetString("textureTrigLevelVS", resourceCulture);
            }
        }
    }
}
